In [100]:
a = [1.0,2.0,1.0]

In [101]:
a[0]

1.0

In [102]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [103]:
import torch
a = torch.ones(3)

In [104]:
a[1]

tensor(1.)

In [105]:
float(a[1])

1.0

In [106]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [107]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] =1.0


In [108]:
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [109]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [110]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [111]:
points.shape


torch.Size([3, 2])

In [112]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [113]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [114]:
points[0,1]

tensor(1.)

In [115]:
points[0]

tensor([4., 1.])

In [116]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [117]:
points_storage = points.storage()
points_storage[0]

4.0

In [118]:
points.storage()[1]

1.0

In [119]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [120]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [121]:
second_point.size()

torch.Size([2])

In [122]:
second_point.shape

torch.Size([2])

In [123]:
points.stride()

(2, 1)

In [124]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [125]:
second_point.storage_offset()

2

In [126]:
second_point.stride()

(1,)

In [127]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0]=10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [128]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0]=10.0
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [129]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [130]:
id(points.storage()) == id(points_t.storage())

True

In [131]:
points.stride()

(2, 1)

In [132]:
points_t.stride()

(1, 2)

In [133]:
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [134]:
transpose_t.shape

torch.Size([5, 4, 3])

In [135]:
some_t.stride()

(20, 5, 1)

In [136]:
transpose_t.stride()

(1, 5, 20)

In [137]:
points.is_contiguous()

True

In [138]:
points_t.is_contiguous()

False

In [139]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [140]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [141]:
points_t.stride()

(1, 2)

In [142]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [143]:
points_t_cont.stride()

(3, 1)

In [144]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [145]:
double_points = torch.ones(10,2, dtype = torch.double)
short_points = torch.tensor([[1,2],[3,4]], dtype = torch.short)

In [146]:
short_points.dtype

torch.int16

In [147]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [148]:
double_points = torch.ones(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype= torch.short)

In [149]:
points_64 = torch.rand(5,dtype = torch.double)
points_short = points_64.to(torch.short)
points_64 = points_short

In [150]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [151]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]


[1, 3]

In [152]:
points[1:]
points[1:,:]
points[1:,0]
points[None]


tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [153]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [154]:
points = torch.from_numpy(points_np)

In [155]:

torch.save(points,'../InputData/ch2/ourpoints.t')

In [156]:
with open('../InputData/ch2/ourpoints.t','wb') as f:
    torch.save(points, f)

In [157]:
points = torch.load('../InputData/ch2/ourpoints.t')

In [158]:
with open('../InputData/ch2/ourpoints.t','rb') as f:
    points=torch.load(f)

In [159]:
import h5py

f = h5py.File('../InputData/ch2/ourpoints.hdf5','w')
dset = f.create_dataset('coords', data = points.numpy())
f.close()

In [160]:
f = h5py.File('../InputData/ch2/ourpoints.hdf5','r')
dset = f['coords']
last_points = dset[-2:]

In [161]:
last_points = torch.from_numpy(dset[-2:])
f.close()


In [162]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [163]:
points_gpu = points.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [164]:
points_gpu = points.to(device='cuda:0')

AssertionError: Torch not compiled with CUDA enabled

In [165]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [166]:
points_gpu = points_gpu + 4

NameError: name 'points_gpu' is not defined

In [86]:

points_cpu = points_gpu.to(device='cpu')

NameError: name 'points_gpu' is not defined

In [87]:

points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

AssertionError: Torch not compiled with CUDA enabled

In [88]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

In [89]:
a.shape, a_t.shape


(torch.Size([3, 2]), torch.Size([2, 3]))

In [90]:



a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [91]:

a = torch.ones(3, 2)

In [93]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])